### ISSUE TITLE
Card field view area in browser blinks continuously

### ISSUE THREAD

**Issue by electric-bungalow** [ankipalace/advanced-browser#122]
The card preciew area of the browser continuously blinks when I have this add-on enabled. Prevents me from using the browser at all.

**Comment by ijgnd** [comment]
thanks for your report.

Do you still have this problem with the current Anki version 2.1.49 and the latest version of the advanced broser add-on from ankiweb?

A lot of problems in Anki occur because of add-on conflicts - I mean there are about 1000 add-ons and no creator can check any combination ...

If you still have this problem read https://faqs.ankiweb.net/when-problems-occur.html

Then disable all other add-ons, restart Anki and try again. Do you still have this add-on? If so it's not about the advanced browser.

If the problem only occurs when the Advanced broser is enabled (while all other add-ons are disabled), does it occur for all notes or only for some. Some weird code in your card templates might be involved so also make some notes of an unmodified basic notetype and tell us whether these also produce flickering.

Keep in mind that after enabling/disabling an add-on you must restart Anki so that the changes take effect.

**Comment by ijgnd** [comment]
If you still have this problem please reopen this issue. I'm only closing it for now to get a better overview of the issue list.
