### ISSUE TITLE
Left-align column

### ISSUE THREAD

**Issue by vwkd** [ankipalace/advanced-browser#131]
The left alignment of columns was reverted to center alignment in updating for Anki 2.1.45, see commit https://github.com/ankipalace/advanced-browser/commit/01cb415ab42da01d2ca36a75a503ce1607fea59f. The left alignment was introduced after a discussion in #8.

Can we restore left alignment?

**Comment by ijgnd** [comment]
fixed with https://github.com/ankipalace/advanced-browser/commit/bc4ea9595a398241c19681ab041b5941e1ec01c7

thanks for creating this fix - I also prefer left-aligned columns a lot ...

Could you help test the latest master branch of this add-on so that we can tell ankingmed when he can upload the new version to ankiweb.
