### ISSUE TITLE
re-open: "OR" does not work in searchfield 

### ISSUE THREAD

**Issue by honis56** [ankipalace/advanced-browser#137]
https://github.com/ankipalace/advanced-browser/issues/127

Sorry, I still have the problem even though I updated.

As I found out, it occurs together with the addon "Ignore accents in browser search".

https://ankiweb.net/shared/info/1924690148

Best regards

**Comment by ijgnd** [comment]
Have you tried deleting the advanced browser and just using the one add-on "Ignore accents in browser search"?

Then Anki breaks for me, too. This makes senese. The latest version for the ignore accents add-on is from 2020-11. At that time anki 2.1.35 was the latest version and since then the search feature of anki was rewritten and as as arthur said in #127 the advanced browser does not modify the search in any way.

you seem to have run into this known issue: : https://github.com/hssm/anki-ignore-accents/issues/6
