### ISSUE TITLE
Error when opening browser

### ISSUE THREAD

**Issue by Sol0din** [ankipalace/advanced-browser#139]
Hello,
Since I have updated to anki 2.1.49 (linux) this addon provokes the following error when I try to open the browser :

DbError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"near \\\"select\\\": syntax error\"))", kind: Other }

I tried to reinstall the addon but it doesn't fix it, only disabling the addon fixes the problem
Thank you for looking into this

**Comment by ijgnd** [comment]
Your problem seems to be similar to the following know bug, https://github.com/ankipalace/advanced-browser/issues/112#issuecomment-859633842: 

In the browser clicking on the "Overdue Interval" tab will trigger the following pop up error and make the cards disappear in the browser.

    DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("near \"select\": syntax error"))", kind: Other }

Other subsequent browsing related action will then keep trigger the error and cards won't show up.
**However as soon as you click on another sorting option the cards appear again and the error stops popping up.**

&nbsp;

If your problem is not similar please let us know. When you test this make sure to disable all other add-ons and restart anki to rule out interferences from another add-on, see https://faqs.ankiweb.net/when-problems-occur.html
