### ISSUE TITLE
2.1.41-2.1.44 branch is broken

### ISSUE THREAD

**Issue by abdnh** [ankipalace/advanced-browser#151]
After testing #148 and #149, I went to test the 2.1.41-2.1.44 branch and hit another error.

![image](https://user-images.githubusercontent.com/41397710/192544039-32b9a06e-3651-4021-8248-85d984b95d52.png)

The aqt.operations submodule was [added in 2.1.45](https://github.com/ankitects/anki/commit/3a6f2a993ef0c3a06a015735f7376bbc5c0ab75d), so this branch is probably broken in all versions it claims to support.

**Comment by abdnh** [comment]
I'll look into sending a fix for this.

@ijgnd BTW, I see the older AnkiWeb branches are not managed with Git branches here. Maybe they should be uploaded so that it's easier to apply fixes?

**Comment by ijgnd** [comment]
that's an important find. 

I probably should have been more precise when asking ankingmed for uploading your fix.

We should revert to the prior version. As far as I see that was the version from 2021-07-23 though the appropriate commit is 6d4ea7b from 2021-02-22 (the last one before rumovz made the changes for .45). Do you happen to have an old file from ankiweb otherwise I'll zip the repo as of commit 6d4ea7b.

**Comment by ijgnd** [comment]
I'll look into integrating the old branches into git later today.

**Comment by abdnh** [comment]
>  Do you happen to have an old file from ankiweb

No, I don't have the zip.

**Comment by ijgnd** [comment]
since I didn't find an old version to patch I zipped it from an old commit.

the code is identical (apart from yesterday's patch) to the AB code I have in a backup from 2021-07.

github doesn't allow to upload .ankiaddon files so I added the extension .zip which must be removed before using this file.

[advanced_browser__git_6d4ea7b_from_2021-02-22__Version_39__forAnki41-44__with_abdnhs_overdue_fix_license.ankiaddon.zip](https://github.com/ankipalace/advanced-browser/files/9656919/advanced_browser__git_6d4ea7b_from_2021-02-22__Version_39__forAnki41-44__with_abdnhs_overdue_fix_license.ankiaddon.zip)

**Comment by ijgnd** [comment]
ankingmed will upload the patched version lateer today.

**Comment by ijgnd** [comment]
@abdnh 

> @ijgnd BTW, I see the older AnkiWeb branches are not managed with Git branches here. Maybe they should be uploaded so that it's easier to apply fixes?

I added git branches corresponding to the ankiweb releases of AB, see [my new comment on top of the readme.md file](https://github.com/ankipalace/advanced-browser/commit/c91e5d464e0460c06f6e5dbf86855ae17e7d3495). To the branches for Anki 2.1.24+ I applied your overdue ivl patches. 

I hope this is what you had in mind.
