### ISSUE TITLE
Cannot copy and paste via right click mouse, but via ctrl+c or without addons it is okay.

### ISSUE THREAD

**Issue by honis56** [ankipalace/advanced-browser#157]
Fehler
Es ist ein Fehler aufgetreten. Bitte starten Sie Anki neu und halten Sie während des Startvorgangs die Umschalttaste gedrückt, damit Anki die installierten Erweiterungen temporär deaktiviert.
Wenn das Problem nur auftritt, wenn die Erweiterungen aktiviert sind, dann benutzen Sie bitte den Menueintrag Extras > Erweiterungen um die problembehaftete Erweiterung durch selektives Deaktivieren herauszufinden.
Wenn Sie die entsprechende Erweiterung herausgefunden haben, dann bitten wir, dass Sie sich mit einem entsprechenden Problembericht an die Support-Seite für Erweiterungen wenden, damit der Fehler behoben werden kann.
Debuginformationen:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-11-19 15:01:38

Caught exception:
Traceback (most recent call last):
  File "xxxx... AppData\Roaming\Anki2\addons21\spell_checker\editor.py", line 163, in contextMenuEvent
    data = self._page.contextMenuData()
AttributeError: 'AnkiWebPage' object has no attribute 'contextMenuData'

**Comment by ijgnd** [comment]
The problem is not with advanced browser.

The bottom of the error message shows that the problem comes from the add-on "spell_checker". You seem to use a version of this add-on from around 2019. In PyQt6 most add-ons switched form using contextMenuData to lastContextMenuRequest. And you use Anki 2.1.54 built with PyQt 6.3

you should send this error message to the creator of the add-on spellchecker. I think it's gluanimate and I think the repo might be https://github.com/glutanimate/spell-checker-public/issues . 

In the summer glutanimate talked about updating this add-on and possibly integrating it into anki, see https://github.com/ankitects/anki/issues/1938#issuecomment-1169538153.

I'm closing this. If you still think that Advanced Browser causes this reopen this and provide more details, e.g. if this still happens if all other add-ons are disabled and you have restarted Anki.
